package lab10;

public enum TokenType {
	EOF, IDENT, NUM, SKIP, IN, FOR, PRINT, PREFIX, VAR, PLUS, TIMES, ASSIGN, OPEN_PAR, CLOSE_PAR, STMT_SEP, EXP_SEP, OPEN_BLOCK, CLOSE_BLOCK, MINUS, OPEN_LIST, CLOSE_LIST
}
